# Labels applied by paths changed in a PR (actions/labeler@v5)

docs:
  - changed-files:
      - any-glob-to-any-file:
          - README.md
          - docs/**/*

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/**/*

test:
  - changed-files:
      - any-glob-to-any-file:
          - tests/**/*

chore:
  - changed-files:
      - any-glob-to-any-file:
          - .editorconfig
          - .gitattributes
          - .gitignore
          - .pre-commit-config.yaml
          - pyproject.toml
          - .github/ISSUE_TEMPLATE/**/*
          - .github/PULL_REQUEST_TEMPLATE/**/*
          - .github/dependabot.yml
          - .github/labeler.yml
